name: Clang

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: 'Exporting llvm PATH'
      run: echo "`pwd`/llvm-16/bin" >> $GITHUB_PATH
    - name: Install clang-16
      run: make -f Makefile.clang install-clang-16-for-ubuntu
    - name: Update submodules
      run: git submodule update --init
    - name: Build contract
      run: make -f Makefile.clang all
    - name: Run omni_lock tests
      run: cd tests/omni_lock_rust && cargo test
